### ISSUE TITLE
[WinError 123]

### ISSUE THREAD

**Issue by wolfwitte** [renerocksai/rj2obs#3]
Hi there, running the script converted part of my archive but it stopped inbetween with the following:

`C:\Users\wolfw\AppData\Local\Programs\Python\Python39>python r2o.py roam.json
Pass 1: scan all pages
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 678/678 [00:00<00:00, 43598.90it/s]
Pass 2: track blockrefs
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 678/678 [00:00<00:00, 21689.88it/s]
Pass 3: generate
  0%|                                                                                                                             | 0/678 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\wolfw\AppData\Local\Programs\Python\Python39\r2o.py", line 162, in <module>
    os.makedirs(d, exist_ok=True)
  File "C:\Users\wolfw\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'md\\https:'`

~~Could this be caused by special German characters (ä,ö,ü,ß)?~~ Update: It cannot, since some of these were converted.

**Comment by wolfwitte** [comment]
Update: When importing from a Markdown-Backup, i got Windows-error-messages for every file containing a colon (":"), i am guessing this happened with the script as well. I am now adjusting all note-titles containing a colon.

**Comment by renerocksai** [comment]
Sorry for the late reply. The script converts notes to files named like their titles - and Windows unfortunately can't handle colons in filenames, as colons are used in drive specs, like `C:`. A more thorough script would rename those titles and fix all links.
